### ISSUE TITLE
What is the reason for removal of nan dependancy?

### ISSUE THREAD

**Issue by metabench** [mateogianolio/nblas#4]
I'm looking into updating some of my OpenCL node code, and seeing that I need to change it because of changes to nan. I have written all of my node c++ code using nan, but am now considering the alternative.

Did you find a performance increase by not using nan?

**Comment by mateogianolio** [comment]
Three main reasons (also see my answer [here](https://github.com/codeforscience/webdata/issues/7#issuecomment-196985719)):

1. nan's raison d'être is to make it easier to compile node addons across versions, but they themselves made changes to their API at least once that broke a lot of old nan code. For example, they changed the way you read contents from TypedArray's. I'd rather just keep up with changes in V8, than keep up with changes in V8 **and** nan.
2. This library requires node version >=4.0, after which V8 has been stable and I haven't needed to update the library since (except for some minor polishing unrelated to V8).
3. The building process is much faster (at least 2x, but I haven't measured).

To answer your last question, I haven't measured the runtime performance before and after switching to V8-only but I don't think it's that big of a difference.

**Comment by metabench** [comment]
Did you look at any particular examples, tutorials, best practise reference, or existing projects that show best practise?

I'm considering making a project or two that add 1 to a number or an array of numbers, to isolate the complexity of the interface between node and C++. I'm not all that advanced in terms of understanding C++ and V8 together, but can write fast algorithms in C and C++, so I need to find a way to make the links between the languages easy to correctly put in place. While I have got some working code that uses the newer nan version, I thought it would be worth comparing notes with you, @mateogianolio, on what the best approach is.

One possible result will be better documentation for programmers who can program JavaScript and C++, but are not that great at C++ and V8. Documentation I have been pointed towards when I asked some more detailed questions, such as the V8 docs, have been difficult (but interesting) for me to understand. With the documentation and tools being as they are, perhaps the best advice for me would be to improve my V8 knowledge - but that is not where I particularly wish to focus, and I'd really prefer to know the least amount possible about V8 in order to get the results I need.

I'll work on an `addone_nan` project to start with.

**Comment by metabench** [comment]
@mateogianolio I have invited you to collaborate on two projects:

https://github.com/metabench/addone
https://github.com/metabench/addone_nan

Currently both of them just add 1 to an integer. I intend these projects to be places where interface code gets tried and tested. I still want the operations to all be to add 1, but I plan on making use of some other functionality such as SIMD and OpenCL.
